import { h } from 'what-framework';
import { renderToString } from 'what-framework/server';
import { routes, sessions, site, speakers } from '../content.mjs';

export function publicRoutes(){ return routes.map((route)=>route.path); }
export function renderRoute(path, origin='http://localhost:4173'){
  const session=sessions.find((item)=>path===`/sessions/${item.slug}`);
  const speaker=speakers.find((item)=>path===`/speakers/${item.slug}`);
  let body=session?Session(session):speaker?Speaker(speaker):path==='/'?Home():path==='/agenda'?Agenda():path==='/speakers'?Speakers():path==='/build'?Build():NotFound();
  let title=session?`${session.title} — Beacon`:speaker?`${speaker.name} — Beacon`:site.name;
  return `<!doctype html>${renderToString(Layout({path,title,origin,body}))}`;
}
function Layout({path,title,origin,body}){return h('html',{lang:'en'},h('head',{},h('meta',{charset:'utf-8'}),h('meta',{name:'viewport',content:'width=device-width, initial-scale=1'}),h('title',{},title),h('meta',{name:'description',content:site.description}),h('link',{rel:'canonical',href:new URL(path,origin).toString()}),h('link',{rel:'stylesheet',href:'/site.css'}),h('script',{type:'module',src:'/assets/main.js',defer:true})),h('body',{},h('header',{class:'shell mast'},h('a',{class:'brand',href:'/'},'Beacon'),h('nav',{class:'nav','aria-label':'Primary'},h('a',{href:'/agenda'},'Agenda'),h('a',{href:'/speakers'},'Speakers'),h('a',{href:'/build'},'Build'))),h('main',{},body),h('footer',{class:'shell footer'},'Fictional event · local agenda · valid ICS export'),h('script',{id:'beacon-data',type:'application/json'},JSON.stringify({sessions,speakers}))))}
function Home(){return h('div',{class:'shell'},h('section',{class:'hero agenda-lead'},h('div',{},h('p',{class:'eyeline'},'Independent technology conference'),h('h1',{},'Agenda first. Calendar ready.'),h('p',{},site.description),h('a',{class:'button',href:'/agenda'},'Build agenda')),h('div',{class:'panel next-card'},h('p',{class:'eyeline'},'Next session · EDT'),h('time',{datetime:sessions[0].starts},time(sessions[0].starts,'America/New_York')),h('h2',{},sessions[0].title),h('p',{},sessions[0].summary))),Schedule(sessions))}
function Agenda(){return h('div',{class:'shell'},h('section',{class:'hero agenda-lead'},h('div',{},h('p',{class:'eyeline'},'Schedule'),h('h1',{},'Filter, save, export.'),h('p',{},'Static session content is enhanced by a local personal agenda island.')),h('div',{class:'panel next-card'},h('p',{class:'eyeline'},'Timezone tools'),h('p',{},'Switch the schedule display, save sessions locally, then export a VCALENDAR file without a server.'))),h('section',{id:'agenda-island',class:'panel'},h('p',{},'Agenda loading…'),Schedule(sessions)))}
function Schedule(items){return h('div',{class:'schedule'},...groupByDay(items).map(([dayLabel,daySessions])=>h('section',{class:'day-group'},h('h2',{},dayLabel),...daySessions.map((session)=>h('a',{class:'session',href:`/sessions/${session.slug}`},h('time',{datetime:session.starts},time(session.starts,'America/New_York')),h('div',{},h('p',{class:'meta'},`${session.topic} · ${room(session)}`),h('h3',{},session.title),h('p',{},session.summary)),h('span',{class:'details-pill'},'Details'))))))}
function Session(session){const speaker=speakers.find((item)=>item.slug===session.speaker);return h('div',{class:'shell hero'},h('div',{},h('p',{class:'eyeline'},`${session.topic} · ${room(session)}`),h('h1',{},session.title),h('p',{},session.summary),h('p',{},`${speaker?.name} · ${time(session.starts,'America/New_York')} · ${session.minutes} min`),h('a',{class:'button',href:'/agenda'},'Add on agenda page')),h('div',{class:'burst','aria-hidden':'true'}))}
function Speakers(){return h('div',{class:'shell'},h('section',{class:'hero'},h('div',{},h('p',{class:'eyeline'},'Speaker roster'),h('h1',{},'People making small systems vivid.'))),h('div',{class:'speaker-grid'},...speakers.map((speaker)=>h('a',{class:'speaker',href:`/speakers/${speaker.slug}`},h('p',{class:'meta'},speaker.role),h('h3',{},speaker.name),h('p',{},speaker.bio)))))}
function Speaker(speaker){return h('div',{class:'shell hero'},h('div',{},h('p',{class:'eyeline'},speaker.role),h('h1',{},speaker.name),h('p',{},speaker.bio),h('a',{class:'button',href:'/agenda'},'See agenda')),h('div',{class:'burst','aria-hidden':'true'}))}
function Build(){return h('div',{class:'shell hero'},h('div',{},h('p',{class:'eyeline'},'Public build journal'),h('h1',{},'How Beacon is assembled.')),h('div',{class:'panel'},h('ul',{},h('li',{},'Signals: topic, timezone, saved session ids, storage mode and ICS status.'),h('li',{},'Computed: filtered agenda and VCALENDAR text.'),h('li',{},'Effects: local agenda persistence through safe wrappers.'),h('li',{},'Snippet: `makeIcs(savedSessions)` emits `BEGIN:VCALENDAR`, one `VEVENT` per saved session, escaped summary/location fields and UTC stamps.'),h('li',{},'Problem fixed during refinement: pressed filter buttons now have an explicit `aria-pressed` style and schedule row links only underline titles on hover/focus.'),h('li',{},'Refinement: static and client schedules are grouped by day with non-wrapping timezone-aware time labels.'),h('li',{},'Routing: sessions and speakers generate direct static routes.'),h('li',{},'Vura: `dist/manifest.json` is validated with the public manifest contract and maps each route to `config.staticKey` in `dist/static`.'),h('li',{},'Lesson: client mount enhances static schedule HTML; it is not SSR-preserving hydration.'),h('li',{},'Limitation: fictional event, local-only agenda, no ticketing or analytics.'))))}
function NotFound(){return h('div',{class:'shell hero'},h('div',{},h('p',{class:'eyeline'},'No signal'),h('h1',{},'This beacon is dark.'),h('p',{},'Return to the agenda to keep planning.'),h('a',{class:'button',href:'/agenda'},'Open agenda')))}
function room(session){return session.room}
function time(value,zone){return new Intl.DateTimeFormat('en',{timeZone:zone,month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(value))}
function day(value,zone='America/New_York'){return new Intl.DateTimeFormat('en',{timeZone:zone,month:'short',day:'numeric'}).format(new Date(value))}
function groupByDay(items){const groups=new Map();for(const session of items){const key=day(session.starts);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(session)}return [...groups.entries()]}
