import { h } from 'what-framework';
import { renderToString } from 'what-framework/server';
import { routes, sessions, site, speakers } from '../content.mjs';

export function publicRoutes(){ return routes.map((route)=>route.path); }
export function renderRoute(path, origin='http://localhost:4173'){
  const session=sessions.find((item)=>path===`/sessions/${item.slug}`);
  const speaker=speakers.find((item)=>path===`/speakers/${item.slug}`);
  let body=session?Session(session):speaker?Speaker(speaker):path==='/'?Home():path==='/agenda'?Agenda():path==='/speakers'?Speakers():path==='/build'?Build():NotFound();
  let title=session?`${session.title} — Beacon`:speaker?`${speaker.name} — Beacon`:site.name;
  return `<!doctype html>${renderToString(Layout({path,title,origin,body}))}`;
}
function Layout({path,title,origin,body}){return h('html',{lang:'en'},h('head',{},h('meta',{charset:'utf-8'}),h('meta',{name:'viewport',content:'width=device-width, initial-scale=1'}),h('title',{},title),h('meta',{name:'description',content:site.description}),h('link',{rel:'canonical',href:new URL(path,origin).toString()}),h('link',{rel:'stylesheet',href:'/site.css'}),h('script',{type:'module',src:'/assets/main.js',defer:true})),h('body',{},h('header',{class:'shell mast'},h('a',{class:'brand',href:'/'},'Beacon'),h('nav',{class:'nav','aria-label':'Primary'},h('a',{href:'/agenda','aria-current':path==='/agenda'?'page':path.startsWith('/sessions/')?'location':undefined},'Agenda'),h('a',{href:'/speakers','aria-current':path==='/speakers'?'page':path.startsWith('/speakers/')?'location':undefined},'Speakers'),h('a',{href:'/build','aria-current':path==='/build'?'page':undefined},'Build'))),h('main',{},body),h('footer',{class:'shell footer'},'Fictional event · local agenda · valid ICS export'),h('script',{id:'beacon-data',type:'application/json'},JSON.stringify({sessions,speakers}))))}
function Home(){return h('div',{class:'shell'},h('section',{class:'hero agenda-lead'},h('div',{},h('p',{class:'eyeline'},'Independent technology conference'),h('h1',{},'Agenda first. Calendar ready.'),h('p',{},'Two days of small systems, expressive interfaces and practical conversations. Explore this fictional program and keep a personal agenda in your browser.'),h('a',{class:'button',href:'/agenda'},'Build agenda')),h('div',{class:'panel next-card'},h('p',{class:'eyeline'},'Sample opening session · EDT'),h('time',{datetime:sessions[0].starts},time(sessions[0].starts,'America/New_York')),h('h2',{},sessions[0].title),h('p',{},sessions[0].summary))),Schedule(sessions))}
function Agenda(){return h('div',{class:'shell'},h('section',{class:'hero agenda-lead'},h('div',{},h('p',{class:'eyeline'},'Schedule'),h('h1',{},'Filter, save, export.'),h('p',{},'Plan a personal conference schedule with local saves, timezone previews and calendar export.')),h('div',{class:'panel next-card'},h('p',{class:'eyeline'},'Timezone tools'),h('p',{},'Switch the schedule display, save sessions locally, then export a VCALENDAR file without a server.'))),h('section',{id:'agenda-island',class:'panel'},h('p',{},'Agenda loading…'),Schedule(sessions)))}
function Schedule(items){return h('div',{class:'schedule'},...groupByDay(items).map(([dayLabel,daySessions])=>h('section',{class:'day-group'},h('h2',{},dayLabel),...daySessions.map((session)=>h('a',{class:'session',href:`/sessions/${session.slug}`},h('time',{datetime:session.starts},time(session.starts,'America/New_York')),h('div',{},h('p',{class:'meta'},`${session.topic} · ${room(session)}`),h('h3',{},session.title),h('p',{},session.summary)),h('span',{class:'details-pill'},'Details'))))))}
function Session(session){const speaker=speakers.find((item)=>item.slug===session.speaker);return h('div',{class:'shell hero session-detail'},h('article',{},h('p',{class:'eyeline'},`${session.topic} · ${room(session)}`),h('h1',{},session.title),h('p',{},session.summary),h('p',{},h('a',{href:`/speakers/${speaker.slug}`},speaker.name),` · ${time(session.starts,'America/New_York')} · ${session.minutes} min`),...session.abstract.map(text=>h('p',{},text)),h('a',{class:'button',href:`/agenda?session=${session.slug}`},'Add on agenda page')),h('aside',{class:'panel'},h('p',{class:'eyeline'},session.format),h('h2',{},'Take away'),h('ul',{},...session.outcomes.map(text=>h('li',{},text))),h('h3',{},'Who it is for'),h('p',{},session.audience),h('p',{class:'meta'},'Fictional conference session · times shown in EDT')))}
function Speakers(){return h('div',{class:'shell'},h('section',{class:'hero'},h('div',{},h('p',{class:'eyeline'},'Speaker roster'),h('h1',{},'People making small systems vivid.'))),h('div',{class:'speaker-grid'},...speakers.map((speaker)=>h('a',{class:'speaker',href:`/speakers/${speaker.slug}`},h('p',{class:'meta'},speaker.role),h('h3',{},speaker.name),h('p',{},speaker.bio)))))}
function Speaker(speaker){return h('div',{class:'shell hero session-detail'},h('article',{},h('p',{class:'eyeline'},speaker.role),h('h1',{},speaker.name),h('p',{},speaker.bio),h('a',{class:'button',href:'/speakers'},'All speakers')),h('aside',{class:'panel'},h('h2',{},'At Beacon'),...sessions.filter(session=>session.speaker===speaker.slug).map(session=>h('section',{},h('p',{class:'meta'},`${time(session.starts,'America/New_York')} · ${session.minutes} min`),h('h3',{},h('a',{href:`/sessions/${session.slug}`},session.title)),h('p',{},session.summary)))))}
function Build(){return h('div',{class:'shell hero build-layout'},h('div',{},h('p',{class:'eyeline'},'Public build journal'),h('h1',{},'How Beacon is assembled.')),h('div',{class:'panel'},h('ul',{},h('li',{},h('code',{},'makeIcs(savedSessions, generatedAt)'),': UTC events, CRLF lines and UTF-8-aware 75-byte folding from src/calendar.mjs.'),h('li',{},'Calendar export creates a text/calendar Blob and a download anchor for beacon-agenda.ics while retaining the preview. The prior text-only output did not produce a file.'),h('li',{},'Speaker and session records link both ways; ?session=slug offers an explicit save and saved-only view. Static details remain useful without JavaScript.'),h('li',{},'Signals: topic, timezone, saved session ids, storage mode and ICS status.'),h('li',{},'Computed: filtered agenda and VCALENDAR text.'),h('li',{},'Effects: local agenda persistence through safe wrappers.'),h('li',{},'Snippet: `makeIcs(savedSessions)` emits `BEGIN:VCALENDAR`, one `VEVENT` per saved session, escaped summary/location fields and UTC stamps.'),h('li',{},'Problem fixed during refinement: pressed filter buttons now have an explicit `aria-pressed` style and schedule row links only underline titles on hover/focus.'),h('li',{},'Problem fixed during sourcegate: mounted agenda rows now keep a session Details link separate from the Save button, and the browser smoke clicks that link after JavaScript mounts.'),h('li',{},'Refinement: static and client schedules are grouped by day with non-wrapping timezone-aware time labels.'),h('li',{},'Routing: sessions and speakers generate direct static routes.'),h('li',{},'Vura: `dist/manifest.json` is validated with the public manifest contract and maps each route to `config.staticKey` in `dist/static`.'),h('li',{},'Lesson: client mount enhances static schedule HTML; it is not SSR-preserving hydration.'),h('li',{},'Limitation: fictional event, local-only agenda, no ticketing or analytics.'))))}
function NotFound(){return h('div',{class:'shell hero'},h('div',{},h('p',{class:'eyeline'},'No signal'),h('h1',{},'This beacon is dark.'),h('p',{},'Return to the agenda to keep planning.'),h('a',{class:'button',href:'/agenda'},'Open agenda')))}
function room(session){return session.room}
function time(value,zone){return new Intl.DateTimeFormat('en',{timeZone:zone,month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(value))}
function day(value,zone='America/New_York'){return new Intl.DateTimeFormat('en',{timeZone:zone,month:'short',day:'numeric'}).format(new Date(value))}
function groupByDay(items){const groups=new Map();for(const session of items){const key=day(session.starts);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(session)}return [...groups.entries()]}
