import { createServer } from 'node:http';
import { existsSync, mkdirSync, readFileSync, statSync } from 'node:fs';
import { extname, join } from 'node:path';
import { chromium } from 'playwright';

const root=join(process.cwd(),'dist/static');mkdirSync('.screenshots',{recursive:true});
const server=createServer((req,res)=>{const url=new URL(req.url,'http://localhost');let file=join(root,decodeURIComponent(url.pathname));if(!extname(file))file=join(file,'index.html');if(!existsSync(file)||statSync(file).isDirectory())file=join(root,'404.html');res.setHeader('content-type',contentType(file));res.statusCode=file.endsWith('404.html')&&!url.pathname.startsWith('/404')?404:200;res.end(readFileSync(file));});
await new Promise((resolve)=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch();const failures=[];async function check(name,fn){try{await fn();console.log(`ok ${name}`)}catch(e){failures.push(`${name}: ${e.message}`);console.log(`FAIL ${name}: ${e.message}`)}}
try{
 await check('desktop routes and direct details load without console errors',async()=>{const page=await browser.newPage({viewport:{width:1360,height:920}});const errors=[];page.on('console',(msg)=>{if(msg.type()==='error')errors.push(msg.text())});for(const path of ['/', '/agenda','/sessions/state-at-the-edge','/speakers/mina-orbit','/build']){const res=await page.goto(`${base}${path}`,{waitUntil:'networkidle'});if(res.status()!==200)throw new Error(`${path} status ${res.status()}`);if(await page.locator('h1').count()!==1)throw new Error(`${path} h1 count`);if(path==='/')await page.screenshot({path:'.screenshots/beacon-desktop.png',fullPage:true});}if(errors.length)throw new Error(errors.join(' | '));await page.close();});
 await check('agenda filters, saves and exports valid ICS',async()=>{const page=await browser.newPage();await page.goto(`${base}/agenda`,{waitUntil:'networkidle'});await page.getByRole('button',{name:'platform'}).click();if(await page.locator('.session').count()!==2)throw new Error('platform filter failed');await page.locator('.session button').first().click();await page.locator('select').selectOption('Europe/London');await page.getByRole('button',{name:'Export ICS'}).click();const ics=await page.locator('#ics-export').inputValue();if(!ics.includes('BEGIN:VCALENDAR')||!ics.includes('BEGIN:VEVENT')||!ics.includes('SUMMARY:State at the edge'))throw new Error(`bad ics ${ics}`);await page.close();});
 await check('mounted agenda keeps session detail navigation separate from save',async()=>{const page=await browser.newPage();await page.goto(`${base}/agenda`,{waitUntil:'networkidle'});await page.waitForSelector('.session-title-link');await page.getByRole('link',{name:/State at the edge/}).click();await page.waitForURL('**/sessions/state-at-the-edge');if(await page.locator('h1').textContent()!=='State at the edge')throw new Error('detail navigation landed on wrong page');await page.close();});
 await check('390px mobile hero and agenda panels do not overlap or overflow',async()=>{const page=await browser.newPage({viewport:{width:390,height:820},isMobile:true});for(const path of ['/', '/agenda', '/build']){await page.goto(`${base}${path}`,{waitUntil:'networkidle'});if(path==='/build')await page.addStyleTag({content:'html{font-family:Verdana,\"DejaVu Sans\",sans-serif!important}'});const result=await page.evaluate(()=>{const width=Math.max(document.body.scrollWidth,document.documentElement.scrollWidth);const h1=document.querySelector('h1')?.getBoundingClientRect();const card=document.querySelector('.next-card')?.getBoundingClientRect();const overlap=!!(h1&&card&&!(card.top>=h1.bottom||h1.top>=card.bottom||card.left>=h1.right||h1.left>=card.right));return{width,overlap,h1Width:h1?.width||0};});if(result.width>390)throw new Error(`${path} width ${result.width}`);if(result.overlap)throw new Error(`${path} hero/card overlap`);if(result.h1Width<=0)throw new Error(`${path} collapsed h1 width`);}await page.close();});
 await check('corrupt and denied storage keep agenda usable',async()=>{const corrupt=await browser.newPage();await corrupt.addInitScript(()=>localStorage.setItem('beacon-agenda','{\"bad\":true}'));await corrupt.goto(`${base}/agenda`,{waitUntil:'networkidle'});if(await corrupt.locator('.session').count()<4)throw new Error('corrupt storage broke agenda');await corrupt.close();const denied=await browser.newPage({viewport:{width:390,height:820},isMobile:true});await denied.addInitScript(()=>{const bad=()=>{throw new DOMException('denied','SecurityError')};Storage.prototype.getItem=bad;Storage.prototype.setItem=bad;});await denied.goto(`${base}/agenda`,{waitUntil:'networkidle'});await denied.locator('.session button').first().click();await denied.getByRole('button',{name:'Export ICS'}).click();if(!(await denied.locator('#ics-export').inputValue()).includes('VCALENDAR'))throw new Error('denied storage ics failed');if(await denied.locator('.storage-note').evaluate((n)=>n.hidden))throw new Error('storage boundary hidden');await denied.screenshot({path:'.screenshots/beacon-mobile.png',fullPage:true});await denied.close();});
 await check('unknown path returns genuine 404',async()=>{const res=await fetch(`${base}/dark-stage`);const html=await res.text();if(res.status!==404)throw new Error(`status ${res.status}`);if(!html.includes('beacon is dark'))throw new Error('404 copy missing');});
}finally{await browser.close();server.close();}
if(failures.length){console.error(failures.join('\n'));process.exit(1)}
function contentType(file){if(file.endsWith('.css'))return'text/css';if(file.endsWith('.js'))return'text/javascript';return'text/html; charset=utf-8'}
